//===- Ada300HLOps.cpp - Ada300 High-Level Dialect Op Definitions ---------===//
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
//===----------------------------------------------------------------------===//
//
// Provides the verifier bodies for Ada300HL ops.  The bulk of each op's
// implementation is generated by tablegen from Ada300HLOps.td; this file
// supplies only the hand-written verifier logic referenced via
// `let hasVerifier = 1`.
//
//===----------------------------------------------------------------------===//

#include "Ada300HL/Ada300HLOps.h"
#include "Ada300HL/Ada300HLDialect.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"

using namespace mlir;
using namespace buddy::ada300hl;

//===----------------------------------------------------------------------===//
// Tablegen-generated op definitions
//===----------------------------------------------------------------------===//

#define GET_OP_CLASSES
#include "Ada300HL/Ada300HLOps.cpp.inc"

//===----------------------------------------------------------------------===//
// PwnlOp
//===----------------------------------------------------------------------===//

LogicalResult PwnlOp::verify() {
  SegmentCount seg = getSegments();
  if (seg != SegmentCount::seg16 && seg != SegmentCount::seg32)
    return emitOpError("'segments' must be 16 or 32, got ")
           << static_cast<int>(seg);
  return success();
}

//===----------------------------------------------------------------------===//
// TensorMmaOp
//===----------------------------------------------------------------------===//

LogicalResult TensorMmaOp::verify() {
  if (getRowSize() <= 0)
    return emitOpError("'row_size' must be a positive integer");
  if (getColSize() <= 0)
    return emitOpError("'col_size' must be a positive integer");
  if (getAccSize() <= 0)
    return emitOpError("'acc_size' must be a positive integer");
  if (getBlkCntA() <= 0)
    return emitOpError("'blk_cnt_a' must be a positive integer");
  if (getBlkCntW() <= 0)
    return emitOpError("'blk_cnt_w' must be a positive integer");
  return success();
}
