//===- ada300-rxops-main.cpp - Ada300 rx-ops path runner ------------------===//
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
//===----------------------------------------------------------------------===//
//
// Minimal runner for the Ada300 example compiled via the rx-ops library-call
// path (lower-ada300hl-to-rxops).
//
// Usage:
//   ada300-rxops-runner <arg0.data> [input_value]
//
//   arg0.data  – binary file of 16576 float32 model parameters (produced by
//                ada300-import.py)
//   input_value – optional float to fill the 1x64 input tensor (default 1.0)
//
// The program calls _mlir_ciface_forward (generated by -llvm-request-c-wrappers
// from forward.mlir) which in turn calls _mlir_ciface_subgraph0 (compiled from
// the Ada300HL → rx-ops lowered MLIR).
//
//===----------------------------------------------------------------------===//

#include <buddy/Core/Container.h>

#include <chrono>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <iostream>
#include <stdexcept>
#include <vector>

// ---------------------------------------------------------------------------
// Model constants
// ---------------------------------------------------------------------------
static constexpr size_t ParamsSize = 16576;  // floats in arg0.data
static constexpr size_t InputRows  = 1;
static constexpr size_t InputCols  = 64;
static constexpr size_t OutputCols = 64;

// ---------------------------------------------------------------------------
// Declaration of the MLIR-generated forward function.
// The signature is determined by forward.mlir after -llvm-request-c-wrappers:
//   func.func @forward(%params: memref<16576xf32>, %in: memref<1x64xf32>)
//                   -> memref<1x64xf32>
// becomes:
//   void _mlir_ciface_forward(StridedMemRefType<float,1>  *params,
//                             StridedMemRefType<float,2>  *input,
//                             StridedMemRefType<float,2> **result)
// ---------------------------------------------------------------------------
extern "C" void _mlir_ciface_forward(MemRef<float, 2> *output,
                                     MemRef<float, 1> *params,
                                     MemRef<float, 2> *input);

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------
static void loadParams(const std::string &path, MemRef<float, 1> &params) {
  std::ifstream f(path, std::ios::binary);
  if (!f)
    throw std::runtime_error("Cannot open params file: " + path);
  f.read(reinterpret_cast<char *>(params.getData()),
         sizeof(float) * params.getSize());
  if (!f)
    throw std::runtime_error("Failed to read params file: " + path);
  std::cout << "[Log] Loaded " << params.getSize() << " params from " << path
            << "\n";
}

// ---------------------------------------------------------------------------
// main
// ---------------------------------------------------------------------------
int main(int argc, char **argv) {
  if (argc < 2) {
    std::cerr << "Usage: " << argv[0] << " <arg0.data> [input_value]\n";
    return 1;
  }

  const std::string paramsPath = argv[1];
  const float inputVal = (argc >= 3) ? std::stof(argv[2]) : 1.0f;

  // ---- Allocate and load parameters ----------------------------------------
  MemRef<float, 1> params({ParamsSize});
  loadParams(paramsPath, params);

  // ---- Allocate input (1 x 64), fill with inputVal -------------------------
  MemRef<float, 2> input({InputRows, InputCols});
  for (size_t i = 0; i < InputRows * InputCols; ++i)
    input.getData()[i] = inputVal;

  // ---- Allocate output (1 x 64), zero-initialised --------------------------
  MemRef<float, 2> output({InputRows, OutputCols});
  std::memset(output.getData(), 0, sizeof(float) * InputRows * OutputCols);

  // ---- Run inference -------------------------------------------------------
  std::cout << "[Log] Running inference (input=" << inputVal << ")...\n";
  const auto t0 = std::chrono::high_resolution_clock::now();

  _mlir_ciface_forward(&output, &params, &input);

  const auto t1 = std::chrono::high_resolution_clock::now();
  const double ms =
      std::chrono::duration<double, std::milli>(t1 - t0).count();
  std::cout << "[Log] Inference time: " << ms << " ms\n";

  // ---- Print output --------------------------------------------------------
  std::cout << "[Log] Output (1x" << OutputCols << "):\n  [";
  float *out = output.getData();
  for (size_t i = 0; i < OutputCols; ++i) {
    std::cout << out[i];
    if (i + 1 < OutputCols)
      std::cout << ", ";
  }
  std::cout << "]\n";

  return 0;
}
